### ISSUE TITLE
sometimes broken gui

### ISSUE THREAD

**Issue by RobTranquillo** [offenesdresden/annotieren#5]
Nach dem Annotieren ist manchmal die Textdarstellung zerbrochen.

![bug-annotation](https://cloud.githubusercontent.com/assets/311739/14652874/a50a3fe8-0676-11e6-9db6-9b81aa68587d.png)

**Comment by RobTranquillo** [comment]
![bug-annotation2](https://cloud.githubusercontent.com/assets/311739/14653931/a559432c-067b-11e6-9e05-af1a75023106.png)

**Comment by astro** [comment]
Pls recheck.
